# Generated by Django 5.0.4 on 2024-04-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardstory', '0002_alter_storymodel_priority_alter_storymodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'TO_DO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('HOLD', 'HOLD'), ('QA', 'QA'), ('PO_REVIEW', 'PO_REVIEW'), ('COMPLETED', 'COMPLETED')], max_length=20),
        ),
    ]
