# Generated by Django 5.0.4 on 2024-04-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardstory', '0003_alter_storymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymodel',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storymodel',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
